import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://fluentish.com'
  
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/courses',
          '/institutions',
          '/about',
          '/features',
          '/pricing',
          '/contact',
          '/search',
          '/students-public',
          '/institutions-public',
          '/auth/signin',
          '/auth/signup',
          '/forgot-password',
          '/institution-registration',
          '/offline',
        ],
        disallow: [
          '/admin/',
          '/institution/',
          '/student/',
          '/dashboard/',
          '/api/',
          '/_next/',
          '/manifest.json',
          '/sw.js',
          '/temp/',
          '/uploads/',
          '/test-',
          '/mobile-testing/',
          '/test-service-worker/',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/courses',
          '/institutions',
          '/about',
          '/features',
          '/pricing',
          '/contact',
          '/search',
          '/students-public',
          '/institutions-public',
        ],
        disallow: [
          '/admin/',
          '/institution/',
          '/student/',
          '/dashboard/',
          '/api/',
          '/_next/',
          '/auth/',
          '/temp/',
          '/uploads/',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/courses',
          '/institutions',
          '/about',
          '/features',
          '/pricing',
          '/contact',
          '/search',
          '/students-public',
          '/institutions-public',
        ],
        disallow: [
          '/admin/',
          '/institution/',
          '/student/',
          '/dashboard/',
          '/api/',
          '/_next/',
          '/auth/',
          '/temp/',
          '/uploads/',
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  }
} 