import { PrismaClient } from '@prisma/client';
import { logger } from '../lib/logger';

const prisma = new PrismaClient();

async function checkInstitutionImages() {
  try {
    console.log('Checking institution images in database...\n');

    // Get all institutions
    const institutions = await prisma.institution.findMany({
      select: {
        id: true,
        name: true,
        logoUrl: true,
        mainImageUrl: true,
        facilities: true,
      },
    });

    console.log(`Found ${institutions.length} institutions:\n`);

    institutions.forEach((institution, index) => {
      console.log(`${index + 1}. ${institution.name} (ID: ${institution.id})`);
      console.log(`   Logo URL: ${institution.logoUrl || 'NULL'}`);
      console.log(`   Main Image URL: ${institution.mainImageUrl || 'NULL'}`);
      
      if (institution.facilities) {
        try {
          const facilities = JSON.parse(institution.facilities as string);
          console.log(`   Facility Images: ${facilities.length} images`);
        } catch (error) {
          console.log(`   Facility Images: Error parsing JSON`);
        }
      } else {
        console.log(`   Facility Images: NULL`);
      }
      console.log('');
    });

    // Summary
    const withLogo = institutions.filter(i => i.logoUrl).length;
    const withMainImage = institutions.filter(i => i.mainImageUrl).length;
    const withFacilities = institutions.filter(i => {
      if (!i.facilities) return false;
      try {
        const facilities = JSON.parse(i.facilities as string);
        return facilities.length > 0;
      } catch {
        return false;
      }
    }).length;

    console.log('Summary:');
    console.log(`- Institutions with logo: ${withLogo}/${institutions.length}`);
    console.log(`- Institutions with main image: ${withMainImage}/${institutions.length}`);
    console.log(`- Institutions with facility images: ${withFacilities}/${institutions.length}`);

    if (withMainImage === 0) {
      console.log('\n⚠️  No institutions have a main image uploaded!');
      console.log('The main image you see on public pages is a placeholder SVG generated by the system.');
      console.log('To add a real main image, use the institution profile form or admin edit form.');
    }

  } catch (error) {
    logger.error('Error checking institution images:');
  } finally {
    await prisma.$disconnect();
  }
}

// Run the script
checkInstitutionImages(); 