-- Create Live Conversation Tables (Tables Only)
-- This script creates the necessary tables for the Live Conversations feature

-- Live Conversations table
CREATE TABLE IF NOT EXISTS `live_conversations` (
  `id` varchar(36) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text,
  `conversationType` varchar(50) NOT NULL,
  `language` varchar(50) NOT NULL,
  `level` varchar(20) NOT NULL,
  `startTime` datetime(3) NOT NULL,
  `endTime` datetime(3) NOT NULL,
  `duration` int NOT NULL,
  `maxParticipants` int NOT NULL DEFAULT 8,
  `currentParticipants` int NOT NULL DEFAULT 0,
  `price` double NOT NULL DEFAULT 0,
  `isPublic` boolean NOT NULL DEFAULT true,
  `isFree` boolean NOT NULL DEFAULT false,
  `status` varchar(20) NOT NULL DEFAULT 'SCHEDULED',
  `meetingUrl` varchar(500),
  `meetingId` varchar(100),
  `meetingPassword` varchar(100),
  `instructorId` varchar(36),
  `hostId` varchar(36) NOT NULL,
  `topic` varchar(255),
  `culturalNotes` text,
  `vocabularyList` json,
  `grammarPoints` json,
  `conversationPrompts` json,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `metadata` json,
  PRIMARY KEY (`id`),
  KEY `live_conversations_instructorId_idx` (`instructorId`),
  KEY `live_conversations_hostId_idx` (`hostId`),
  KEY `live_conversations_startTime_idx` (`startTime`),
  KEY `live_conversations_status_idx` (`status`),
  KEY `live_conversations_language_idx` (`language`),
  KEY `live_conversations_level_idx` (`level`),
  KEY `live_conversations_conversationType_idx` (`conversationType`),
  KEY `live_conversations_isFree_idx` (`isFree`),
  CONSTRAINT `live_conversations_instructorId_fkey` FOREIGN KEY (`instructorId`) REFERENCES `user` (`id`) ON DELETE SET NULL,
  CONSTRAINT `live_conversations_hostId_fkey` FOREIGN KEY (`hostId`) REFERENCES `user` (`id`) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Live Conversation Participants table
CREATE TABLE IF NOT EXISTS `live_conversation_participants` (
  `id` varchar(36) NOT NULL,
  `conversationId` varchar(36) NOT NULL,
  `userId` varchar(36) NOT NULL,
  `joinedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `leftAt` datetime(3),
  `duration` int NOT NULL DEFAULT 0,
  `isInstructor` boolean NOT NULL DEFAULT false,
  `isHost` boolean NOT NULL DEFAULT false,
  `status` varchar(20) NOT NULL DEFAULT 'JOINED',
  `speakingTime` int NOT NULL DEFAULT 0,
  `messageCount` int NOT NULL DEFAULT 0,
  `feedback` json,
  `metadata` json,
  PRIMARY KEY (`id`),
  UNIQUE KEY `live_conversation_participants_conversationId_userId_key` (`conversationId`, `userId`),
  KEY `live_conversation_participants_conversationId_idx` (`conversationId`),
  KEY `live_conversation_participants_userId_idx` (`userId`),
  KEY `live_conversation_participants_status_idx` (`status`),
  CONSTRAINT `live_conversation_participants_conversationId_fkey` FOREIGN KEY (`conversationId`) REFERENCES `live_conversations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `live_conversation_participants_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `user` (`id`) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Live Conversation Messages table
CREATE TABLE IF NOT EXISTS `live_conversation_messages` (
  `id` varchar(36) NOT NULL,
  `conversationId` varchar(36) NOT NULL,
  `senderId` varchar(36) NOT NULL,
  `recipientId` varchar(36),
  `content` text NOT NULL,
  `messageType` varchar(20) NOT NULL DEFAULT 'TEXT',
  `language` varchar(50) NOT NULL,
  `isTranslation` boolean NOT NULL DEFAULT false,
  `originalMessage` varchar(36),
  `timestamp` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `isRead` boolean NOT NULL DEFAULT false,
  `metadata` json,
  PRIMARY KEY (`id`),
  KEY `live_conversation_messages_conversationId_idx` (`conversationId`),
  KEY `live_conversation_messages_senderId_idx` (`senderId`),
  KEY `live_conversation_messages_recipientId_idx` (`recipientId`),
  KEY `live_conversation_messages_timestamp_idx` (`timestamp`),
  KEY `live_conversation_messages_messageType_idx` (`messageType`),
  CONSTRAINT `live_conversation_messages_conversationId_fkey` FOREIGN KEY (`conversationId`) REFERENCES `live_conversations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `live_conversation_messages_senderId_fkey` FOREIGN KEY (`senderId`) REFERENCES `user` (`id`) ON DELETE CASCADE,
  CONSTRAINT `live_conversation_messages_recipientId_fkey` FOREIGN KEY (`recipientId`) REFERENCES `user` (`id`) ON DELETE SET NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Live Conversation Bookings table
CREATE TABLE IF NOT EXISTS `live_conversation_bookings` (
  `id` varchar(36) NOT NULL,
  `conversationId` varchar(36) NOT NULL,
  `userId` varchar(36) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'CONFIRMED',
  `bookedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `cancelledAt` datetime(3),
  `paymentStatus` varchar(20) NOT NULL DEFAULT 'PAID',
  `amount` double NOT NULL DEFAULT 0,
  `currency` varchar(3) NOT NULL DEFAULT 'USD',
  `paymentMethod` varchar(50),
  `transactionId` varchar(255),
  `refundReason` text,
  `metadata` json,
  PRIMARY KEY (`id`),
  UNIQUE KEY `live_conversation_bookings_conversationId_userId_key` (`conversationId`, `userId`),
  KEY `live_conversation_bookings_conversationId_idx` (`conversationId`),
  KEY `live_conversation_bookings_userId_idx` (`userId`),
  KEY `live_conversation_bookings_status_idx` (`status`),
  KEY `live_conversation_bookings_paymentStatus_idx` (`paymentStatus`),
  CONSTRAINT `live_conversation_bookings_conversationId_fkey` FOREIGN KEY (`conversationId`) REFERENCES `live_conversations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `live_conversation_bookings_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `user` (`id`) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; 